"""
Square Terminal API integration.

Reference: https://developer.squareup.com/reference/square/terminal-api

─── FIAT payment flow ────────────────────────────────────────────────────────

  1. POST /v2/terminals/checkouts
       Body: { idempotency_key, checkout: { amount_money, device_options, reference_id } }
       Response: { checkout: { id, status: "PENDING" } }

  2. Poll GET /v2/terminals/checkouts/{id} every ~2 s
       status transitions: PENDING → IN_PROGRESS → COMPLETED | CANCELED | FAILED

  3. COMPLETED  → emit bus.payment_result(tx_id, True, message)
                  emit MDB VEND APPROVED via bus.transaction_event
     CANCELED/FAILED → emit bus.payment_result(tx_id, False, reason)
                        emit MDB VEND DENIED

─── Bitcoin payment flow ─────────────────────────────────────────────────────

  Square Terminal API does not directly support Bitcoin.
  Recommended options (to confirm before going live):

  A) Square Cash App Pay — supports crypto (incl. BTC) at Square terminals.
     API: POST /v2/terminals/checkouts with payment_type CARD_PRESENT,
     then the terminal offers Cash App Pay as a method which allows BTC.
     Docs: https://developer.squareup.com/docs/terminal-api/cash-app-pay

  B) BTCPay Server / OpenNode — run a separate crypto payment processor
     alongside Square. QR code is generated by your own infrastructure;
     Square handles fiat only.

  For now the mock simulates Option A's timing.

─── Required .env variables ──────────────────────────────────────────────────

  SQUARE_ACCESS_TOKEN   from developer.squareup.com > Applications > Credentials
  SQUARE_LOCATION_ID    from Square Dashboard > Locations
  SQUARE_DEVICE_ID      from Square Dashboard > Devices
                        or: GET /v2/devices  (list all paired readers)
  SQUARE_ENVIRONMENT    "sandbox" | "production"

  Sandbox base URL : https://connect.squareupsandbox.com
  Production base URL: https://connect.squareup.com

─── Finding your SQUARE_DEVICE_ID ───────────────────────────────────────────

  curl https://connect.squareupsandbox.com/v2/devices \\
       -H "Authorization: Bearer {SQUARE_ACCESS_TOKEN}" \\
       -H "Square-Version: 2025-01-23"

  Look for "id" under the device that matches your terminal's serial number.

─── What to provide ──────────────────────────────────────────────────────────

  When ready to go live, supply:
    - SQUARE_ACCESS_TOKEN  (sandbox key first for testing)
    - SQUARE_LOCATION_ID
    - SQUARE_DEVICE_ID
    - Confirm whether the Square terminal is set up for Cash App Pay / crypto

"""
import os
from datetime import datetime

from PyQt5.QtCore import QObject, QThread, QTimer, pyqtSignal

from core.bus import bus
from core.models import TransactionEvent


# ─── Mock client (active during development) ─────────────────────────────────

class SquareMockClient(QObject):
    """
    Simulates realistic Square Terminal API timing.
    Swap for SquareClient in main.py when credentials are ready.
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        bus.payment_requested.connect(self._handle)

    # ------------------------------------------------------------------
    def _ev(self, tx_id, delay_ms, source, direction, message, raw=""):
        QTimer.singleShot(delay_ms, lambda: bus.transaction_event.emit(
            tx_id,
            TransactionEvent(datetime.now(), source, direction, message, raw),
        ))

    def _handle(self, tx_id, amount, payment_type):
        cents = int(amount * 100)

        self._ev(tx_id, 0, "SYSTEM", "out", "Payment flow started")

        if payment_type not in ("fiat", "bitcoin"):
            self._ev(tx_id, 0, "SYSTEM", "in",
                     f"ERROR: unknown payment_type '{payment_type}'")
            QTimer.singleShot(100, lambda: bus.payment_result.emit(
                tx_id, False, f"Unknown payment type: {payment_type}"
            ))
            return

        if payment_type == "fiat":
            body = (
                f'{{"idempotency_key": "{tx_id}", "checkout": {{'
                f'"amount_money": {{"amount": {cents}, "currency": "USD"}}, '
                f'"device_options": {{"device_id": "DEVICE_ID_PLACEHOLDER"}}, '
                f'"reference_id": "{tx_id}"}}}}'
            )
            self._ev(tx_id, 300,  "SQUARE", "out",
                     f"POST /v2/terminals/checkouts  ${amount:.2f} USD", body)
            self._ev(tx_id, 900,  "SQUARE", "in",
                     '200 OK — checkout created, status: PENDING',
                     '{"checkout": {"id": "chk_mock_001", "status": "PENDING"}}')
            self._ev(tx_id, 2500, "SQUARE", "in",
                     "GET .../chk_mock_001 → IN_PROGRESS (payment screen shown)")
            self._ev(tx_id, 5500, "SQUARE", "in",
                     "GET .../chk_mock_001 → COMPLETED (card tapped)")
            self._ev(tx_id, 5700, "MDB",    "out",
                     "VEND APPROVED", "0x05 0x00")
            QTimer.singleShot(5900, lambda: bus.payment_result.emit(
                tx_id, True, f"${amount:.2f} card payment completed",
            ))

        elif payment_type == "bitcoin":
            body = (
                f'{{"idempotency_key": "{tx_id}", "checkout": {{'
                f'"amount_money": {{"amount": {cents}, "currency": "USD"}}, '
                f'"device_options": {{"device_id": "DEVICE_ID_PLACEHOLDER"}}, '
                f'"payment_options": {{"crypto_enabled": true}}, '
                f'"reference_id": "{tx_id}"}}}}'
            )
            self._ev(tx_id, 300,  "SQUARE", "out",
                     f"POST /v2/terminals/checkouts  ${amount:.2f} USD (Bitcoin/Crypto)", body)
            self._ev(tx_id, 1000, "SQUARE", "in",
                     "200 OK — checkout created, QR code generated, status: PENDING",
                     '{"checkout": {"id": "chk_mock_btc_001", "status": "PENDING"}}')
            self._ev(tx_id, 2800, "SQUARE", "in",
                     "GET .../chk_mock_btc_001 → IN_PROGRESS (QR displayed, awaiting BTC scan)")
            self._ev(tx_id, 8000, "SQUARE", "in",
                     "GET .../chk_mock_btc_001 → COMPLETED (Bitcoin payment confirmed)")
            self._ev(tx_id, 8200, "MDB",    "out",
                     "VEND APPROVED", "0x05 0x00")
            QTimer.singleShot(8400, lambda: bus.payment_result.emit(
                tx_id, True, f"${amount:.2f} Bitcoin payment completed",
            ))


# ─── Real client (activate when credentials are ready) ───────────────────────

class _PaymentWorker(QThread):
    """Background thread — all Qt signals emitted via these to stay thread-safe."""
    event_ready  = pyqtSignal(str, object)   # tx_id, TransactionEvent
    done         = pyqtSignal(str, bool, str) # tx_id, success, message

    def __init__(self, tx_id, amount, payment_type, base_url, headers, device_id, location_id):
        super().__init__()
        self._tx_id        = tx_id
        self._amount       = amount
        self._payment_type = payment_type
        self._base_url     = base_url
        self._headers      = headers
        self._device_id    = device_id
        self._location_id  = location_id
        self._cancel_requested = False

    def request_cancel(self):
        self._cancel_requested = True

    def _ev(self, source, direction, message, raw=""):
        self.event_ready.emit(
            self._tx_id,
            TransactionEvent(datetime.now(), source, direction, message, raw),
        )

    def run(self):
        import json, uuid, time
        try:
            import requests
        except ImportError:
            self._ev("SYSTEM", "in", "ERROR: 'requests' not installed — pip3 install requests")
            self.done.emit(self._tx_id, False, "requests not installed")
            return

        tx_id  = self._tx_id
        amount = self._amount
        cents  = int(amount * 100)

        checkout_block = {
            "amount_money": {"amount": cents, "currency": "USD"},
            "device_options": {"device_id": self._device_id, "skip_receipt_screen": True},
            "location_id": self._location_id,
            "reference_id": tx_id,
            "note": f"MyGreenStar {tx_id}",
        }
        # Bitcoin: Cash App Pay with crypto enabled (confirm with Square support).
        # Square Terminal API does not natively support BTC — Cash App Pay is the
        # recommended path. payment_options.crypto_enabled signals that intent.
        if self._payment_type == "bitcoin":
            checkout_block["payment_options"] = {"crypto_enabled": True}

        body = {"idempotency_key": str(uuid.uuid4()), "checkout": checkout_block}
        body_str = json.dumps(body, indent=2)
        suffix = " (Bitcoin/Crypto)" if self._payment_type == "bitcoin" else ""
        self._ev("SQUARE", "out",
                 f"POST {self._base_url}/v2/terminals/checkouts  ${amount:.2f} USD{suffix}",
                 body_str)

        try:
            r = requests.post(
                f"{self._base_url}/v2/terminals/checkouts",
                headers=self._headers,
                json=body,
                timeout=15,
            )
            r.raise_for_status()
            data = r.json()
        except Exception as exc:
            self._ev("SQUARE", "in", f"ERROR: {exc}")
            self.done.emit(tx_id, False, str(exc))
            return

        checkout_id = data.get("checkout", {}).get("id")
        if not checkout_id:
            self._ev("SQUARE", "in",
                     f"ERROR: unexpected response shape: {json.dumps(data)[:200]}")
            self.done.emit(tx_id, False, "Unexpected API response — missing checkout.id")
            return
        self._ev("SQUARE", "in",
                 f"200 OK — checkout id={checkout_id}, status: PENDING",
                 json.dumps(data, indent=2))

        # Poll until terminal responds (max 2 min)
        for _ in range(60):
            time.sleep(2)

            if self._cancel_requested:
                self._ev("SYSTEM", "out", "User cancelled — cancelling checkout on terminal")
                self._cancel_checkout(requests, checkout_id)
                self.done.emit(tx_id, False, "Payment cancelled")
                return

            try:
                r = requests.get(
                    f"{self._base_url}/v2/terminals/checkouts/{checkout_id}",
                    headers=self._headers,
                    timeout=10,
                )
                r.raise_for_status()
                d = r.json()
            except Exception as exc:
                self._ev("SQUARE", "in", f"Poll error: {exc}")
                continue

            status = d.get("checkout", {}).get("status", "UNKNOWN")
            self._ev("SQUARE", "in",
                     f"GET /v2/terminals/checkouts/{checkout_id} → {status}")

            if status == "COMPLETED":
                self._ev("MDB", "out", "VEND APPROVED", "0x05 0x00")
                self.done.emit(tx_id, True, f"${amount:.2f} payment completed")
                return

            if status in ("CANCELED", "FAILED"):
                reason = d.get("checkout", {}).get("cancel_reason", status)
                self._ev("MDB", "out", f"VEND DENIED — {reason}", "0x04 0x00")
                self.done.emit(tx_id, False, f"Payment {status.lower()}: {reason}")
                return

        # Timeout — cancel on terminal
        self._ev("SYSTEM", "out", "Timeout — cancelling checkout on terminal")
        self._cancel_checkout(requests, checkout_id)
        self.done.emit(tx_id, False, "Payment timed out after 2 minutes")

    def _cancel_checkout(self, requests, checkout_id):
        try:
            requests.post(
                f"{self._base_url}/v2/terminals/checkouts/{checkout_id}/cancel",
                headers=self._headers,
                timeout=10,
            )
        except Exception:
            pass



class SquareClient(QObject):
    """
    Production Square Terminal client. Auto-selected by make_square_client()
    when SQUARE_ACCESS_TOKEN is present in .env.
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self._token    = os.getenv("SQUARE_ACCESS_TOKEN", "")
        self._location = os.getenv("SQUARE_LOCATION_ID", "")
        self._device   = os.getenv("SQUARE_DEVICE_ID", "")
        env            = os.getenv("SQUARE_ENVIRONMENT", "sandbox")
        self._base_url = (
            "https://connect.squareup.com"
            if env == "production"
            else "https://connect.squareupsandbox.com"
        )
        self._workers = {}  # tx_id → _PaymentWorker, keep alive until thread finishes
        bus.payment_requested.connect(self._handle)
        bus.payment_cancel_requested.connect(self._cancel)

    def _headers(self):
        return {
            "Authorization": f"Bearer {self._token}",
            "Content-Type": "application/json",
            "Square-Version": "2025-01-23",
        }

    def _cancel(self, tx_id):
        w = self._workers.get(tx_id)
        if w:
            w.request_cancel()

    def _handle(self, tx_id, amount, payment_type):
        if bus.crypto_mode or payment_type == "bitcoin":
            return  # CryptoSessionManager handles this payment
        w = _PaymentWorker(
            tx_id, amount, payment_type,
            self._base_url, self._headers(), self._device, self._location,
        )
        self._workers[tx_id] = w
        w.event_ready.connect(bus.transaction_event)
        w.done.connect(bus.payment_result)
        w.finished.connect(lambda worker=w: self._workers.pop(worker._tx_id, None))
        w.start()


def make_square_client(parent=None):
    """
    Returns SquareClient when SQUARE_ACCESS_TOKEN is set in the environment,
    otherwise SquareMockClient. No changes to main.py needed when going live —
    just add the four SQUARE_* vars to .env.
    """
    if os.getenv("SQUARE_ACCESS_TOKEN"):
        import logging
        logging.getLogger(__name__).info(
            "Square: using SquareClient (env=%s)", os.getenv("SQUARE_ENVIRONMENT", "sandbox")
        )
        return SquareClient(parent)
    import logging
    logging.getLogger(__name__).info("Square: SQUARE_ACCESS_TOKEN not set — using SquareMockClient")
    return SquareMockClient(parent)
